## Database Settings
#spring:
#  datasource:
#    url: jdbc:h2:mem:e-commerce-product;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    platform: h2
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
#
#  # H2 Settings
#  h2:
#    console:
#      enabled: true
#      path: /console
#      settings:
#        trace: false
#        web-allow-others: false
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8030/eureka/
#
##spring.main.allow-bean-definition-overriding: true